### ISSUE TITLE
Bug when deleting a user

### ISSUE THREAD

**Issue by rvvergara** [SunnyAsar/faceverse#4]
I tried to delete a user with friendship and friend request records.

ryto.destroy

And here's what happened:

![image](https://user-images.githubusercontent.com/6015315/58222300-2d249400-7d48-11e9-826e-0bf7ca1d095a.png)

And as you will see, the user still didn't get deleted

![image](https://user-images.githubusercontent.com/6015315/58222326-40cffa80-7d48-11e9-8f86-a392c5237149.png)

**Comment by rvvergara** [comment]
Issue still persists when user has an outstanding `friend_request`:

![image](https://user-images.githubusercontent.com/6015315/58299395-ab00a200-7e11-11e9-926d-b2f48732c3d3.png)

**Comment by rvvergara** [comment]
This issue is still persisting. Please fix this guys :)

![image](https://user-images.githubusercontent.com/6015315/58849395-c2b31280-86bc-11e9-903f-5c812b59068e.png)

**Comment by HenryTabima** [comment]
the fix was already implemented, please remember to use destroy instead of delete methods, because delete method doesnt run callbacks

**Comment by rvvergara** [comment]
Ok got it! Indeed `delete` doesn't invoke the callbacks such as `dependent: :destroy`. Great catch!
